#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/cccc-common.sh"

ROOT="$(cccc_repo_root)"
cd "$ROOT"
cccc_init_dirs

TASK="${*:-}"
LANGUAGE="$($SCRIPT_DIR/cccc-detect-language.sh "$TASK")"
NOW="$(cccc_now)"
SKILL_DIR="$(cccc_skill_dir)"
TEMPLATE_DIR="$SKILL_DIR/templates/cccc"

# Generate docs/cccc from templates on first run. Existing files are never overwritten.
for file in project-brief project-map current-state architecture test-strategy roadmap milestone-backlog decision-log risk-register open-questions context-bundle README; do
  target="docs/cccc/${file}.md"
  template="$TEMPLATE_DIR/${file}.template.md"
  if [[ ! -f "$target" ]]; then
    if [[ -f "$template" ]]; then
      cp "$template" "$target"
    else
      cat > "$target" <<EOF2
# $file

Generated by cc-codex-collaborate.

Status: draft
EOF2
    fi
  fi
done

if [[ ! -f docs/cccc/state.json ]]; then
  if [[ -f "$TEMPLATE_DIR/state.template.json" ]]; then
    cp "$TEMPLATE_DIR/state.template.json" docs/cccc/state.json
  else
    echo '{}' > docs/cccc/state.json
  fi
fi

CCCC_TASK="$TASK" CCCC_LANGUAGE="$LANGUAGE" CCCC_NOW="$NOW" python3 - <<'PY'
import json, pathlib, os
p = pathlib.Path('docs/cccc/state.json')
try:
    data = json.loads(p.read_text())
except Exception:
    data = {}
data.update({
    'skill_name': 'cc-codex-collaborate',
    'skill_version': '0.1.2',
    'workspace': 'docs/cccc',
    'task': os.environ.get('CCCC_TASK', ''),
    'user_language': os.environ.get('CCCC_LANGUAGE', 'unknown'),
    'language_source': 'inferred_from_latest_user_message',
    'enabled': True,
    'status': 'DISCOVERING_PROJECT',
    'updated_at': os.environ.get('CCCC_NOW', ''),
})
data.setdefault('mode', 'supervised-auto')
data.setdefault('created_at', os.environ.get('CCCC_NOW', ''))
data.setdefault('project_context_status', 'not_ready')
data.setdefault('roadmap_status', 'not_reviewed')
data.setdefault('current_milestone_id', None)
data.setdefault('completed_milestones', [])
data.setdefault('blocked_milestones', [])
data.setdefault('known_risks', [])
data.setdefault('pause_reason', None)
data.setdefault('stop_hook_continuations', 0)
data.setdefault('thresholds', {
    'max_plan_review_rounds': 3,
    'max_milestones_per_run': 5,
    'max_review_rounds_per_milestone': 3,
    'max_fix_attempts_per_milestone': 3,
    'max_stop_hook_continuations': 10,
    'max_context_refresh_rounds': 3,
    'max_diff_lines_per_milestone': 1200,
    'max_changed_files_per_milestone': 20,
    'on_max_review_exceeded': 'pause'
})
p.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
PY

cat > docs/cccc/runtime/last-init.txt <<EOF2
Initialized at: $NOW
User language: $LANGUAGE
Task: $TASK
EOF2

echo "Initialized cc-codex-collaborate workspace at docs/cccc"
echo "User language: $LANGUAGE"
